[metadata]
name = sr2ml-ravenframework
version = 0.1rc2
description = SR2ML plugin for RAVEN framework
long_description = file: SR2ML/README.md
license_files = SR2ML/LICENSE SR2ML/NOTICE.txt
url = https://github.com/idaholab/SR2ML
authors = [
    {name="Congjian Wang", email="congjian.wang@inl.gov"},
    {name="Diego Mandelli", email="diego.mandelli@inl.gov"}]

[options]
packages =
    SR2ML
    SR2ML/src
    SR2ML/src/Bases
    SR2ML/src/MaintenanceModels
    SR2ML/src/MarginModels
    SR2ML/src/PostProcessors
    SR2ML/src/Reliabilities

python_requires = >=3.9

install_requires =
   raven_framework >=2.2
