
[files]
text_file = "../tests/LER/raw_extract_from_pdf.txt"
entity_file = "../tests/LER/entity.csv"
cause_effect_keywords_file = "../data/cause_effect_keywords.csv"
conjecture_keywords_file = "../data/conjecture_keywords.csv"

status_keywords_file.all = "../data/health_status_keywords.csv"
status_keywords_file.negative = "../data/health_status_keywords_negative.csv"
status_keywords_file.positive = "../data/health_status_keywords_positive.csv"
status_keywords_file.neutral = "../data/health_status_keywords_neutral.csv"

output_health_status_file = "../tests/LER/output_health_status.csv"
output_causal_effect_file = "../tests/LER/output_causal_effect.csv"
